# Generated by Django 4.2.2 on 2023-06-28 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adv_type', models.TextField(blank=True, null=True)),
                ('adv_cod', models.IntegerField(blank=True, null=True)),
                ('initial_price', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('final_price', models.IntegerField()),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('is_occupied', models.BooleanField(blank=True, default=True, null=True)),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('photo_main', models.ImageField(blank=True, null=True, upload_to='img/product')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='img/product')),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('suite_bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('garage', models.IntegerField(blank=True, default=0, null=True)),
                ('useful_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('total_meters', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('caixa_matricula_cef', models.IntegerField(blank=True, null=True)),
                ('caixa_edital', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
