# Generated by Django 4.2.2 on 2023-06-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertising',
            old_name='square_meters',
            new_name='total_meters',
        ),
        migrations.AddField(
            model_name='advertising',
            name='caixa_edital',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertising',
            name='caixa_matricula_cef',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertising',
            name='is_occupied',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='suite_bedrooms',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertising',
            name='useful_meters',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
