# Generated by Django 4.2.2 on 2023-06-28 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisings', '0002_rename_square_meters_advertising_total_meters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='adv_cod',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='caixa_edital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='caixa_matricula_cef',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='garage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='is_occupied',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='suite_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='total_meters',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='useful_meters',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
